---

pipeline:
  - scm:
      type: git
      repository: git@github.com:pagarme/autobahn.git

  - build:
      type: rocker

  - deploy:
      type: kubernetes
      deployment_dir: .
      namespace: "{{ Environment.namespace }}"

environments:
  prd:
    namespace: core-prd
  stg:
    namespace: core-stg

